### PR TITLE
Brief review of various graphical plotting packages

### PR DESCRIPTION
**Pull request by Sisyphuss**
A primary work about #5. Should only be internal use. More presentable work will be done in the future.

### CODE REVIEW

**Comment by waldyrious** [comment]
@Sisyphuss what do you mean by "only internal use"? Would you rather not have this merged yet? Or did you mean something else?

**Comment by Sisyphuss** [comment]
I meant this document is not very pedagogical. However, an ordinary user won't find it very helpful. However, something pedagogical could be built on this document.

**Comment by waldyrious** [comment]
I understand, but do you want it merged or would you rather keep working on it until you consider it ready for public consumption? I for one think it would be a net positive as reference material, even if not pedagogically useful yet.

Another option is to add it as a page in the wiki, rather than checked in the git repo. In fact I see you already started [adding content to the wiki](https://github.com/JuliaPlot/juliaplot_docs/wiki/Graphical-Plotting-Tools), so why don't you just go ahead and add this as another wiki page? :)

**Comment by Sisyphuss** [comment]
@waldyrious I think this can be merged, for I won't be able to work a lot on this issue for the following days. But I will try to help you with your comparison table if I have time. This is exactly the format I was thinking about. And feel free to use information in my document to complete yours.

**Comment by waldyrious** [comment]
Ok. I'll merge, and later we can move everything to the wiki.

**Pull request merged**
